services:
  web:
    image: php:apache
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=webphp
      - MYSQL_USER=lipp
      - MYSQL_PASSWORD=1234
volumes:
  db:
